#!/usr/bin/env python3
"""Stamp the shared site footer into every page.

This file is the single source of truth for the footer's markup and copy.
The matching styles live in assets/css/footer.css.

To change the footer:  edit FOOTER_STRINGS / build_footer() below, then run

    python3 tools/sync_footer.py

Every page gets the same footer, in its own language and with paths correct
for its directory depth. index.html additionally gets data-i18n attributes so
its runtime language switcher keeps working, and its three string dictionaries
are rewritten from FOOTER_STRINGS so nothing drifts.

Pages are rewritten between the markers below; anything you hand-edit inside
them will be overwritten on the next run.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

START = "<!-- footer:start — generated by tools/sync_footer.py, edit there not here -->"
END = "<!-- footer:end -->"

APP_STORE_URL = "https://apps.apple.com/app/showup-it-counts/id6761016399"
PLAY_STORE_URL = "https://play.google.com/store/apps/details?id=com.showup.showupAndroid"
INSTAGRAM_URL = "https://instagram.com/showupcounts"

APPLE_SVG = (
    '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M18.71 19.5c-.83 '
    "1.24-1.71 2.45-3.05 2.47-1.34.03-1.77-.79-3.29-.79-1.53 0-2 .77-3.27.82-1.31.05-2.3-1.32-3.14-2.53C4.25 "
    "17 2.94 12.45 4.7 9.39c.87-1.52 2.43-2.48 4.12-2.51 1.28-.02 2.5.87 3.29.87.78 0 2.26-1.07 "
    "3.8-.91.65.03 2.47.26 3.64 1.98-.09.06-2.17 1.28-2.15 3.81.03 3.02 2.65 4.03 2.68 4.04-.03.07-.42 "
    "1.44-1.38 2.83M13 3.5c.73-.83 1.94-1.46 2.94-1.5.13 1.17-.34 2.35-1.04 3.19-.69.85-1.83 "
    '1.51-2.95 1.42-.15-1.15.41-2.35 1.05-3.11z"/></svg>'
)

PLAY_SVG = (
    '<svg viewBox="0 0 24 24" aria-hidden="true">'
    '<path d="M1.22 0.345C0.947 0.639 0.787 1.089 0.787 1.674V22.326c0 0.585 0.16 1.035 0.433 '
    '1.329l0.07 0.068L13.068 12V11.862L1.29 0.277 1.22 0.345z" fill="#4285F4"/>'
    '<path d="M17 16.003l-3.932-3.934V11.931L17 7.997l0.088 0.05 4.66 2.647c1.33 0.756 1.33 1.993 '
    '0 2.749L17.088 16.09 17 16.003z" fill="#FFBC00"/>'
    '<path d="M17.088 16.09L13.068 12 1.22 23.655c0.439 0.465 1.162 0.522 1.982 0.058L17.088 '
    '16.09z" fill="#EA4335"/>'
    '<path d="M17.088 7.91L3.202 0.287C2.382-0.177 1.659-0.12 1.22 0.345L13.068 12l4.02-4.09z" '
    'fill="#34A853"/>'
    "</svg>"
)

# Every visible string in the footer, per language.
FOOTER_STRINGS = {
    "en": {
        "desc": "Show up together. Share the Grind.",
        "appstore": "App Store",
        "playstore": "Google Play",
        "legal": "Legal",
        "connect": "Connect",
        "privacy": "Privacy Policy",
        "terms": "Terms of Service",
        "pricing": "Pricing",
        "help": "Help Center",
        "contact": "Contact",
        "copyright": "&copy; 2026 Showup. All rights reserved.",
    },
    "ko": {
        "desc": "함께 쇼업하고 성취를 나누는 곳.",
        "appstore": "App Store",
        "playstore": "Google Play",
        "legal": "법적 고지",
        "connect": "연결",
        "privacy": "개인정보처리방침",
        "terms": "이용약관",
        "pricing": "요금제",
        "help": "고객 센터",
        "contact": "문의",
        "copyright": "&copy; 2026 Showup. 모든 권리 보유.",
    },
    "de": {
        "desc": "Show up together. Teile den Grind.",
        "appstore": "App Store",
        "playstore": "Google Play",
        "legal": "Rechtliches",
        "connect": "Verbinden",
        "privacy": "Datenschutz",
        "terms": "Nutzungsbedingungen",
        "pricing": "Preise",
        "help": "Hilfe-Center",
        "contact": "Kontakt",
        "copyright": "&copy; 2026 Showup. Alle Rechte vorbehalten.",
    },
}

# The i18n keys index.html's dictionaries carry for the footer, and where each
# one takes its value from in FOOTER_STRINGS.
INDEX_I18N_KEYS = {
    "footer.desc": "desc",
    "footer.appstore": "appstore",
    "footer.playstore": "playstore",
    "footer.legal": "legal",
    "footer.connect": "connect",
    "nav.privacy": "privacy",
    "footer.terms": "terms",
    "nav.pricing": "pricing",
    "footer.help": "help",
    "footer.contact": "contact",
    "footer.copyright": "copyright",
}

# page -> (language, directory depth). Depth 1 means the page lives in a
# subdirectory and needs "../" to reach the site root.
PAGES = {
    "index.html": ("en", 0),
    "contact.html": ("en", 0),
    "contact-ko.html": ("ko", 0),
    "contact-de.html": ("de", 0),
    "pricing.html": ("en", 0),
    "pricing-ko.html": ("ko", 0),
    "pricing-de.html": ("de", 0),
    "help.html": ("en", 0),
    "help-ko.html": ("ko", 0),
    "help-de.html": ("de", 0),
    "legal/terms.html": ("en", 1),
    "legal/terms-ko.html": ("ko", 1),
    "legal/terms-de.html": ("de", 1),
    "legal/privacy.html": ("en", 1),
    "legal/privacy-ko.html": ("ko", 1),
    "legal/privacy-de.html": ("de", 1),
}

# Footer rules that used to be copy-pasted into every page's inline <style>.
# They now live in assets/css/footer.css and are stripped from the pages.
# .app-store-badge is dead markup-less styling from an earlier footer.
OWNED_SELECTORS = {
    ".footer", ".footer-inner", ".footer-top", ".footer-logo", ".footer-logo img",
    ".footer-brand p", ".footer-links", ".footer-col h4", ".footer-col a",
    ".footer-col a:hover", ".footer-bottom", ".footer-bottom p",
    ".footer-store", ".store-btn", ".store-btn:hover", ".store-btn svg",
    ".app-store-badge", ".app-store-badge:hover", ".app-store-badge svg",
    '[data-theme="light"] .footer', '[data-theme="light"] .footer-col a:hover',
    '[data-theme="light"] .store-btn', '[data-theme="light"] .app-store-badge',
}


def suffix(lang):
    """The filename suffix pages use for a language: '' for English."""
    return "" if lang == "en" else "-" + lang


def build_footer(lang, depth, i18n):
    """Return the footer markup for one page.

    i18n=True adds the data-i18n attributes index.html's language switcher needs.
    """
    s = FOOTER_STRINGS[lang]
    root = "../" * depth
    sfx = suffix(lang)
    legal = root + "legal/" if depth == 0 else ""
    pad = "    " * depth

    def attr(key):
        return ' data-i18n="%s"' % key if i18n else ""

    # index.html rewrites these two hrefs at runtime, and finds them by id.
    privacy_id = ' id="footer-privacy-link"' if i18n else ""
    terms_id = ' id="footer-terms-link"' if i18n else ""

    html = f"""<footer class="footer">
    <div class="footer-inner">
        <div class="footer-top">
            <div class="footer-brand">
                <a href="{root}index.html" class="footer-logo">
                    <img src="{root}assets/images/logo-dark.svg" alt="showup" class="logo-dark">
                    <img src="{root}assets/images/logo-light.svg" alt="showup" class="logo-light">
                </a>
                <p{attr('footer.desc')}>{s['desc']}</p>
                <div class="footer-store">
                    <a href="{APP_STORE_URL}" target="_blank" rel="noopener" class="store-btn">
                        {APPLE_SVG}
                        <span{attr('footer.appstore')}>{s['appstore']}</span>
                    </a>
                    <a href="{PLAY_STORE_URL}" target="_blank" rel="noopener" class="store-btn">
                        {PLAY_SVG}
                        <span{attr('footer.playstore')}>{s['playstore']}</span>
                    </a>
                </div>
            </div>
            <div class="footer-links">
                <div class="footer-col">
                    <h4{attr('footer.legal')}>{s['legal']}</h4>
                    <a href="{legal}privacy{sfx}.html"{privacy_id}{attr('nav.privacy')}>{s['privacy']}</a>
                    <a href="{legal}terms{sfx}.html"{terms_id}{attr('footer.terms')}>{s['terms']}</a>
                </div>
                <div class="footer-col">
                    <h4{attr('footer.connect')}>{s['connect']}</h4>
                    <a href="{INSTAGRAM_URL}" target="_blank" rel="noopener">Instagram</a>
                    <a href="{root}pricing{sfx}.html"{attr('nav.pricing')}>{s['pricing']}</a>
                    <a href="{root}help{sfx}.html"{attr('footer.help')}>{s['help']}</a>
                    <a href="{root}contact{sfx}.html"{attr('footer.contact')}>{s['contact']}</a>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <p{attr('footer.copyright')}>{s['copyright']}</p>
        </div>
    </div>
</footer>"""

    # Re-indent to sit where the page's own <footer> sat.
    return "\n".join(pad + line if line else line for line in html.split("\n"))


RULE = re.compile(r"([^{}]+)\{([^{}]*)\}")


def normalise(selector):
    return re.sub(r"\s+", " ", re.sub(r"/\*.*?\*/", "", selector, flags=re.S)).strip()


def strip_owned_css(css):
    """Drop the footer rules this page no longer needs to carry itself.

    Only rules whose selector list is entirely owned by footer.css are removed,
    so shared rules that merely mention a footer class survive untouched.
    """
    out, pos = [], 0

    def owned(selector):
        parts = [p.strip() for p in normalise(selector).split(",") if p.strip()]
        return bool(parts) and all(p in OWNED_SELECTORS for p in parts)

    # @media blocks first: strip inside them, drop the block if it empties out.
    for m in re.finditer(r"@media[^{]*\{(?:[^{}]|\{[^{}]*\})*\}", css, re.S):
        out.append(css[pos:m.start()])
        block = m.group(0)
        head, inner = block.split("{", 1)
        inner = inner.rsplit("}", 1)[0]
        kept = "".join(
            inner[r.start():r.end()] for r in RULE.finditer(inner) if not owned(r.group(1))
        )
        out.append("" if not kept.strip() else head + "{" + kept + "\n        }")
        pos = m.end()
    out.append(css[pos:])
    css = "".join(out)

    # then the top-level rules
    kept, pos = [], 0
    for r in RULE.finditer(css):
        if owned(r.group(1)):
            kept.append(css[pos:r.start()])
            pos = r.end()
    kept.append(css[pos:])
    css = "".join(kept)

    return re.sub(r"\n\s*\n\s*\n+", "\n\n", css)


def sync(path, lang, depth):
    p = ROOT / path
    text = p.read_text(encoding="utf-8")
    before = text
    root = "../" * depth

    # 1. link the shared stylesheet, just before the page's own <style>
    link = '<link rel="stylesheet" href="%sassets/css/footer.css">' % root
    if link not in text:
        text = text.replace("<style>", '    %s\n\n    <style>' % link, 1)

    # 2. hand the footer rules over to footer.css
    def restyle(m):
        return "<style>" + strip_owned_css(m.group(1)) + "</style>"

    text = re.sub(r"<style>(.*?)</style>", restyle, text, flags=re.S)

    # 3. stamp the footer itself
    block = START + "\n" + build_footer(lang, depth, i18n=(path == "index.html")) + "\n" + "    " * depth + END
    if START in text:
        text = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, text, flags=re.S)
    elif "<footer class=\"footer\">" in text:
        text = re.sub(r'<footer class="footer">.*?</footer>', lambda _: block, text, flags=re.S)
    else:
        # help pages have no footer yet — it goes after the content wrapper
        anchor = text.rindex("</main>")
        close = text.index("</div>", anchor) + len("</div>")
        text = text[:close] + "\n\n    " + block + text[close:]

    # 4. keep index.html's dictionaries in step with FOOTER_STRINGS
    if path == "index.html":
        for code, strings in FOOTER_STRINGS.items():
            start = re.search(r"^        %s: \{$" % code, text, re.M)
            if not start:
                sys.exit("index.html: no '%s:' dictionary found" % code)
            end = text.index("\n        }", start.end())
            chunk = text[start.end():end]
            for key, field in INDEX_I18N_KEYS.items():
                value = strings[field].replace("&copy;", "\\u00a9").replace("'", "\\'")
                chunk = re.sub(
                    r"('%s': )'[^']*'" % re.escape(key),
                    lambda m: m.group(1) + "'" + value + "'",
                    chunk,
                )
            text = text[:start.end()] + chunk + text[end:]

    if text != before:
        p.write_text(text, encoding="utf-8")
    return text != before


if __name__ == "__main__":
    changed = [path for path, (lang, depth) in PAGES.items() if sync(path, lang, depth)]
    print("synced %d page(s)" % len(changed))
    for path in changed:
        print("  " + path)
